### ISSUE TITLE
ModuleNotFoundError: No module named 'psycopg'

### ISSUE THREAD

**Issue by 812781385** [phidatahq/phidata#1033]
This error always comes up: 

(aienv) (base) root@SHIPDT-MS-7E07:/data/workspace/phidata-ollama-serve# python app.py 
Traceback (most recent call last):
  File "/data/workspace/phidata-ollama-serve/app.py", line 8, in <module>
    storage = PgAssistantStorage(table_name="my_assistant", db_url=db_url)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/aienv/lib/python3.11/site-packages/phi/storage/assistant/postgres.py", line 42, in __init__
    _engine = create_engine(db_url)
              ^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/root/.venvs/aienv/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/aienv/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.venvs/aienv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/psycopg.py", line 411, in import_dbapi
    import psycopg
ModuleNotFoundError: No module named 'psycopg'

sys: ['/data/workspace/phidata-ollama-serve', '/data/apps/anaconda/2024.02-1/lib/python311.zip', '/data/apps/anaconda/2024.02-1/lib/python3.11', '/data/apps/anaconda/2024.02-1/lib/python3.11/lib-dynload', '/root/.venvs/aienv/lib/python3.11/site-packages']
psycopg2 2.9.9 (dt dec pq3 ext lo64)
sqlalchemy 2.0.31

**Comment by 812781385** [comment]
pip install psycopg
