### ISSUE TITLE
/cookbook/llms/ollama "Method not allowed" from image.py and tool_call.py

### ISSUE THREAD

**Issue by CPavlis** [phidatahq/phidata#1052]
I do have ollama with llava:latest nomic-embed-text and adrienbrault/...hermies2...

Only  thing I've changed was to add host="127.0.0.1:port" to the llm loads (I'd recommend adding that to the readme's) which allowed assistant.py to work, though pydandic_output.py just hangs, while both image.py and tool_call.py produce the following:

~/ai/pd$ python tool_call.py
⠋ Working...
Traceback (most recent call last):
  File "~/ai/pd/tool_call.py", line 12, in <module>
    assistant.print_response("Whats happening in the US?", markdown=True)
  File "~/ai/pd/lib/python3.10/site-packages/phi/assistant/assistant.py", line 1470, in print_response
    for resp in self.run(message=message, messages=messages, stream=True, **kwargs):
  File "~/ai/pd/lib/python3.10/site-packages/phi/assistant/assistant.py", line 890, in _run
    for response_chunk in self.llm.response_stream(messages=llm_messages):
  File "~/ai/pd/lib/python3.10/site-packages/phi/llm/ollama/chat.py", line 269, in response_stream
    for response in self.invoke_stream(messages=messages):
  File "~/ai/pd/lib/python3.10/site-packages/phi/llm/ollama/chat.py", line 96, in invoke_stream
    yield from self.client.chat(
  File "~/ai/pd/lib/python3.10/site-packages/ollama/_client.py", line 84, in _stream
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: {"detail":"Method Not Allowed"}

**Comment by jacobweiss2305** [comment]
Currently function calling only works with Llama 3.1 https://docs.phidata.com/models/ollama
