### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by YashMeh** [phidatahq/phidata#1089]
I am new to phiData and have been trying to run [this](https://docs.phidata.com/embedder/together) example with together embedder but I have tried many ways and facing this issue for load_text 

` AttributeError: 'NoneType' object has no attribute 'model_dump'`

If someone has faced this issue please let me know how to fix it.

I have tried with the following python versions - 3.12 and 3.9 using venv for creating virtual environments. 
OS - Linux

**Comment by YashMeh** [comment]
Full Stack Trace - 

```
Traceback (most recent call last):
  File "/home/yashmeh/polSumm/test.py", line 17, in <module>
    pol.load_text("The sky is blue")
  File "/home/yashmeh/polSumm/lib/python3.9/site-packages/phi/knowledge/base.py", line 163, in load_text
    self.load_documents(documents=[Document(content=text)], upsert=upsert, skip_existing=skip_existing)
  File "/home/yashmeh/polSumm/lib/python3.9/site-packages/phi/knowledge/base.py", line 120, in load_documents
    self.vector_db.insert(documents=documents_to_load)
  File "/home/yashmeh/polSumm/lib/python3.9/site-packages/phi/vectordb/pgvector/pgvector2.py", line 157, in insert
    document.embed(embedder=self.embedder)
  File "/home/yashmeh/polSumm/lib/python3.9/site-packages/phi/document/base.py", line 28, in embed
    self.embedding, self.usage = _embedder.get_embedding_and_usage(self.content)
  File "/home/yashmeh/polSumm/lib/python3.9/site-packages/phi/embedder/openai.py", line 69, in get_embedding_and_usage
    return embedding, usage.model_dump()
AttributeError: 'NoneType' object has no attribute 'model_dump'
```

**Comment by ysolanky** [comment]
Hello @YashMeh! The fix for this bug is in this PR: https://github.com/phidatahq/phidata/pull/1090. It will be merged with the next phidata release

Thanks for brining this to our attention :)
