### ISSUE TITLE
llama3.1:8b

### ISSUE THREAD

**Issue by MyraBaba** [phidatahq/phidata#1103]
Hi,

How to set model to llama3.1:8b for Local Rag ? 

I cant find a convenient  way to do this

**Comment by WilliamEspegren** [comment]
Hey @MyraBaba, here is how you can [run local Ollama models](https://github.com/phidatahq/phidata/tree/main/cookbook/llms/ollama) with Phidata :)

**Comment by MyraBaba** [comment]
@WilliamEspegren 

(venvPhiData) redel@RedElephant:~/Projects/phidata$ python cookbook/llms/ollama/assistant.py
⠋ Working...
Traceback (most recent call last):
  File "/home/redel/Projects/phidata/cookbook/llms/ollama/assistant.py", line 9, in <module>
    assistant.print_response("Share a quick healthy breakfast recipe.", markdown=True)
  File "/home/redel/Projects/phidata/venvPhiData/lib/python3.10/site-packages/phi/assistant/assistant.py", line 1473, in print_response
    for resp in self.run(message=message, messages=messages, stream=True, **kwargs):
  File "/home/redel/Projects/phidata/venvPhiData/lib/python3.10/site-packages/phi/assistant/assistant.py", line 891, in _run
    for response_chunk in self.llm.response_stream(messages=llm_messages):
  File "/home/redel/Projects/phidata/venvPhiData/lib/python3.10/site-packages/phi/llm/ollama/chat.py", line 271, in response_stream
    for response in self.invoke_stream(messages=messages):
  File "/home/redel/Projects/phidata/venvPhiData/lib/python3.10/site-packages/phi/llm/ollama/chat.py", line 96, in invoke_stream
    yield from self.client.chat(
  File "/home/redel/Projects/phidata/venvPhiData/lib/python3.10/site-packages/ollama/_client.py", line 84, in _stream
    raise ResponseError(e.response.text, e.response.status_code) from None
ollama._types.ResponseError: model "llama3" not found, try pulling it first

I am serving ollama at local llama3.1:8b but above errors given.

**Comment by WilliamEspegren** [comment]
@MyraBaba have you pulled it by running 'ollama run llama3.1'?

**Comment by MyraBaba** [comment]
ollama run llama3.1:8b is running

**Comment by WilliamEspegren** [comment]
@MyraBaba can you share your code?

**Comment by reinside** [comment]
> Hi,
> 
> How to set model to llama3.1:8b for Local Rag ?
> 
> I cant find a convenient way to do this

Hey,

Just edit the file, adding "llama3.1" in the models list:
`cookbook/llms/ollama/rag/app.py`
