### ISSUE TITLE
Tool use failed

### ISSUE THREAD

**Issue by hemanth** [phidatahq/phidata#1119]
```py
from phi.assistant import Assistant
from phi.tools.yfinance import YFinanceTools
from phi.llm.groq import Groq

assistant = Assistant(llm=Groq(model="llama3-8b-8192"),tools=[YFinanceTools(stock_fundamentals=True,income_statements=True, key_financial_ratios=True, analyst_recommendations=True, company_news=True, technical_indicators=True, company_profile=True)], show_tool_calls=True, description="You are an investment analyst that researches stock prices, analyst recommendations, and stock fundamentals.",
instructions=["Format your response using markdown and use tables to display data where possible."],)
assistant.print_response("PYPL", markdown=True)
```

```
❯ python foo.py 
╭──────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Message  │ PYPL                                                                                                                      │
├──────────┼───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│ Response │                                                                                                                           │
│ (1.5s)   │  • Running: get_current_stock_price(symbol=PYPL)                                                                          │
│          │                                                                                                                           │
│          │ Tool use failed: no tool can be called with name get_average_recommendations                                              │
╰──────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```
https://github.com/phidatahq/phidata/blob/94d17ae9d6017060a6809ec799111fbea2a84471/phi/tools/yfinance.py#L26 ^ doesn't have any tool named `get_average_recommendations`

**Comment by PureMath86** [comment]
I'd check the version you are running. The tool seems fine:

 ```python
if analyst_recommendations:
            self.register(self.get_analyst_recommendations)
```

but you have a typo (`get_average_recommendations`).

I tested the tool:

```python
print(assistant.tools)
tools = YFinanceTools(stock_price=True, 
                      analyst_recommendations=True, 
                      stock_fundamentals=True)
print(tools.get_analyst_recommendations("NVDA"))
print(tools.get_current_stock_price("NVDA"))
```

And the output is correct:

{"0":{"period":"0m","strongBuy":7,"buy":14,"hold":15,"sell":1,"strongSell":1},"1":{"period":"-1m","strongBuy":18,"buy":36,"hold":5,"sell":0,"strongSell":0},"2":{"period":"-2m","strongBuy":19,"buy":34,"hold":5,"sell":0,"strongSell":0},"3":{"period":"-3m","strongBuy":12,"buy":21,"hold":12,"sell":2,"strongSell":0}}
106.4700

**Comment by hemanth** [comment]
I updated the package via pip and noticed: 

```python
WARNING  Could not run function get_stock_fundamentals(properties={'symbol': 'PYPL'}, type=object)                                           
ERROR    3 validation errors for get_stock_fundamentals                                                                                      
         symbol                                                                                                                              
           Missing required argument [type=missing_argument, input_value=ArgsKwargs((), {'properti...PL'}, 'type': 'object'}),               
         input_type=ArgsKwargs]                                                                                                              
             For further information visit https://errors.pydantic.dev/2.7/v/missing_argument                                                
         properties                                                                                                                          
           Unexpected keyword argument [type=unexpected_keyword_argument, input_value={'symbol': 'PYPL'}, input_type=dict]                   
             For further information visit https://errors.pydantic.dev/2.7/v/unexpected_keyword_argument                                     
         type                                                                                                                                
           Unexpected keyword argument [type=unexpected_keyword_argument, input_value='object', input_type=str]                              
             For further information visit https://errors.pydantic.dev/2.7/v/unexpected_keyword_argument                                     
         Traceback (most recent call last):                                                                                                  
           File "/Users/hhegadehallimadh/.pyenv/versions/3.10.12/lib/python3.10/site-packages/phi/tools/function.py", line 150, in execute   
             self.result = self.function.entrypoint(**self.arguments)                                                                        
           File "/Users/hhegadehallimadh/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pydantic/validate_call_decorator.py", line 59, 
         in wrapper_function                                                                                                                 
             return validate_call_wrapper(*args, **kwargs)                                                                                   
           File "/Users/hhegadehallimadh/.pyenv/versions/3.10.12/lib/python3.10/site-packages/pydantic/_internal/_validate_call.py", line 81,
         in __call__                                                                                                                         
             res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))                                       
         pydantic_core._pydantic_core.ValidationError: 3 validation errors for get_stock_fundamentals                                        
         symbol                                                                                                                              
           Missing required argument [type=missing_argument, input_value=ArgsKwargs((), {'properti...PL'}, 'type': 'object'}),               
         input_type=ArgsKwargs]                                                                                                              
             For further information visit https://errors.pydantic.dev/2.7/v/missing_argument                                                
         properties                                                                                                                          
           Unexpected keyword argument [type=unexpected_keyword_argument, input_value={'symbol': 'PYPL'}, input_type=dict]                   
             For further information visit https://errors.pydantic.dev/2.7/v/unexpected_keyword_argument                                     
         type                                                                                                                                
           Unexpected keyword argument [type=unexpected_keyword_argument, input_value='object', input_type=str]                              
             For further information visit https://errors.pydantic.dev/2.7/v/unexpected_keyword_argument       
     
```

**Comment by LONGYKING** [comment]
also having this same issue, tool use only works for openAi models and fails for Groq and the rest

**Comment by jacobweiss2305** [comment]
@hemanth can you try with Agent class we made a lot of improvements

**Comment by hemanth** [comment]
@jacobweiss2305 would love too, is there a doc link about using some of the open models or maybe ollama on local?
