### ISSUE TITLE
Failed to authenticate with phidata

### ISSUE THREAD

**Issue by homeidjsc** [phidatahq/phidata#1273]
I've just followed the guide in: https://github.com/phidatahq/phidata/tree/main/cookbook/playground

(aienv)$ phi auth

----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 49367)
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.11/socketserver.py", line 317, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/opt/anaconda3/lib/python3.11/socketserver.py", line 348, in process_request
    self.finish_request(request, client_address)
  File "/opt/anaconda3/lib/python3.11/socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/opt/anaconda3/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/opt/anaconda3/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/opt/anaconda3/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/opt/anaconda3/lib/python3.11/site-packages/phi/cli/auth_server.py", line 50, in do_POST
    phi_cli_settings.tmp_token_path.touch(exist_ok=True)
  File "/opt/anaconda3/lib/python3.11/pathlib.py", line 1108, in touch
    fd = os.open(self, flags, mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/macbook/.phi/tmp_token'
----------------------------------------

How to workaround this issue? 

Any suggestion is highly appriciated.

**Comment by vndr** [comment]
@homeidjsc
Create dir with empty file: `~/.phi/tmp_token`, then rerun `phi auth`. Copy url into browser, login,  then it should work, at least that worked for me.

**Comment by ashpreetbedi** [comment]
@vndr good catch

**Comment by ashpreetbedi** [comment]
thank you @vndr , just fixed in 2.5.8

How did you catch this, its insane how good you are!!
