### ISSUE TITLE
Error while using Gemini model

### ISSUE THREAD

**Issue by huxiaoxu2019** [phidatahq/phidata#1509]
## Summary
I got this error while using the Gemini model
Error:
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/middleware/errors.py", line 187, in __call__
    raise exc
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/middleware/errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/middleware/cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    await response(scope, receive, send)
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/responses.py", line 252, in __call__
    async with anyio.create_task_group() as task_group:
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/responses.py", line 255, in wrap
    await func()
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/starlette/responses.py", line 244, in stream_response
    async for chunk in self.body_iterator:
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/phi/playground/router.py", line 244, in chat_response_streamer
    async for run_response_chunk in run_response:
  File "/Users/username/.pyenv/versions/3.11.6/envs/ai2/lib/python3.11/site-packages/phi/agent/agent.py", line 1970, in _arun
    async for model_response_chunk in model_response_stream:  # type: ignore
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
```

Source code:
```
from phi.agent import Agent
from phi.tools.yfinance import YFinanceTools
from phi.playground import Playground, serve_playground_app
from phi.model.google import Gemini, GeminiOpenAIChat

finance_agent = Agent(
    name="Finance Agent",
    model=Gemini(id="gemini-1.5-flash"),
    debug_mode=True
)

app = Playground(agents=[finance_agent]).get_app()

if __name__ == "__main__":
    serve_playground_app("playground:app", reload=True)
```

Anyone can help to take a look at this?

**Comment by manthanguptaa** [comment]
Hey @huxiaoxu2019, I am going to try to replicate the issue today and help you a resolution!

**Comment by samyogdhital** [comment]
@manthanguptaa with `use_async` to `False`, you can run gemini model without tooluse.
But when you try to give a tool access it creates error.
![image](https://github.com/user-attachments/assets/ac1de52f-ef43-4985-bf99-7c70da7d553e)
This below error is from tool use.
 Is it possible to let that `use_async` to `True` and also be able to use `tools`?

**Comment by samyogdhital** [comment]
@ysolanky sure and will let you know.

**Comment by samyogdhital** [comment]
@ysolanky I updated the phidata to latest with `pip install -U phidata`.
But still getting the same problem.

![image](https://github.com/user-attachments/assets/1c2b4f0d-3ed0-4ad4-881c-04249d916c2f)
This is working with both `use_async` true and fasle and with tool enabled and disabled.

![image](https://github.com/user-attachments/assets/9c71502f-5aa9-4a92-a090-3c98664f30b4)

**Comment by ysolanky** [comment]
Hey @samyogdhital I was able to replicate your error with the following Agent config:
```
from phi.agent import Agent
from phi.tools.yfinance import YFinanceTools
from phi.playground import Playground, serve_playground_app
from phi.model.google import Gemini

finance_agent = Agent(
    name="Finance Agent",
    model=Gemini(id="gemini-2.0-flash-exp"),
    tools=[YFinanceTools(stock_price=True)],
    debug_mode=True
)

app = Playground(agents=[finance_agent]).get_app(use_async=False)

if __name__ == "__main__":
    serve_playground_app("playground:app", reload=True)
```

It is working for normal messages but breaks down for tool calls with the following error: `pydantic_core._pydantic_core.PydanticSerializationError: Unable to serialize unknown type: <class 'proto.marshal.collections.repeated.RepeatedComposite'>`. This is due to the structure of the response returned from Google. Thanks for bringing this to out attention. We are going to start work on a fix right away.

**Comment by samyogdhital** [comment]
Hey @ysolanky, is this issue being worked on?
Is it merged already?
