### ISSUE TITLE
Exception in ASGI application When using agent through UI

### ISSUE THREAD

**Issue by zaizou** [phidatahq/phidata#1533]
I receive this error when I try using the agent in UI interface.
"Error in streamResponse: network error"

Some Logs :
```
INFO:     127.0.0.1:56533 - "GET /v1/playground/status HTTP/1.1" 200 OK
INFO:     127.0.0.1:56533 - "OPTIONS /v1/playground/agent/sessions/b8f7ddb5-6014-402b-9e05-b454faedc5b4 HTTP/1.1" 200 OK
INFO:     127.0.0.1:56533 - "POST /v1/playground/agent/sessions/b8f7ddb5-6014-402b-9e05-b454faedc5b4 HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:56533 - "GET /v1/playground/agent/get HTTP/1.1" 200 OK
INFO:     127.0.0.1:56533 - "POST /v1/playground/agent/sessions/all HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:56533 - "POST /v1/playground/agent/run HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application

```

The code 

```
from phi.agent import Agent
from phi.model.openai import OpenAIChat
from phi.model.mistral import MistralChat
from phi.tools.duckduckgo import DuckDuckGo
from phi.playground import Playground, serve_playground_app


web_agent = Agent(
    name="Web Agent",
    model=MistralChat(id="mistral-small-latest",api_key='ujtjt44LwmyQWjQgeMpGq6xL4BDjJlGm'),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    show_tool_calls=True,
    markdown=True,
)
#web_agent.print_response("Whats happening in France? please show results in French and give french sources", stream=True)


app = Playground(agents=[web_agent]).get_app()

if __name__ == "__main__":
    serve_playground_app("websearchagent:app", reload=True)


```

```
Traceback (most recent call last):
  File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\responses.py", line 259, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\responses.py", line 255, in wrap
    await func()
  File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\responses.py", line 232, in listen_for_disconnect
    message = await receive()
              ^^^^^^^^^^^^^^^
  File "C:\Users\myuser\miniconda3\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 563, in receive
    await self.message_event.wait()
  File "C:\Users\myuser\miniconda3\Lib\asyncio\locks.py", line 212, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 24f9bcaf020

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\applications.py", line 113, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
  |     raise exc
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
  |     await self.app(scope, receive, _send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
  |     await self.simple_response(scope, receive, send, request_headers=headers)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
  |     await self.app(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\routing.py", line 715, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\routing.py", line 735, in app
  |     await route.handle(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\routing.py", line 288, in handle
  |     await self.app(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\routing.py", line 76, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
  |     raise exc
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\routing.py", line 74, in app
  |     await response(scope, receive, send)
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\responses.py", line 252, in __call__
  |     async with anyio.create_task_group() as task_group:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\myuser\miniconda3\Lib\site-packages\anyio\_backends\_asyncio.py", line 763, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\responses.py", line 255, in wrap
    |     await func()
    |   File "C:\Users\myuser\miniconda3\Lib\site-packages\starlette\responses.py", line 244, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "C:\Users\myuser\miniconda3\Lib\site-packages\phi\playground\router.py", line 400, in chat_response_streamer
    |     async for run_response_chunk in run_response:
    |   File "C:\Users\myuser\miniconda3\Lib\site-packages\phi\agent\agent.py", line 2120, in _arun
    |     async for model_response_chunk in model_response_stream:  # type: ignore
    |                                       ^^^^^^^^^^^^^^^^^^^^^
    | TypeError: 'async for' requires an object with __aiter__ method, got coroutine
    +------------------------------------


```

**Comment by MichaelXF** [comment]
Getting same error with Claude model, but strangely OpenAI and Ollama models are working fine in playground

**Comment by zaizou** [comment]
Indeed, I forgot to Say that the model used was Mistral

**Comment by epicalxyz** [comment]
Same issue here but with Ollama

**Comment by manthanguptaa** [comment]
Hey @epicalxyz @zaizou @MichaelXF, I will try to replicate the issue today and support you with a hopeful resolution!

**Comment by manthanguptaa** [comment]
Hey @zaizou, can you try running this code 

```
from phi.agent import Agent
from phi.model.openai import OpenAIChat
from phi.model.mistral import MistralChat
from phi.tools.duckduckgo import DuckDuckGo
from phi.playground import Playground, serve_playground_app


web_agent = Agent(
    name="Web Agent",
    model=MistralChat(id="mistral-small-latest",api_key='ujtjt44LwmyQWjQgeMpGq6xL4BDjJlGm'),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    show_tool_calls=True,
    markdown=True,
)
#web_agent.print_response("Whats happening in France? please show results in French and give french sources", stream=True)


app = Playground(agents=[web_agent]).get_app(use_async=False)

if __name__ == "__main__":
    serve_playground_app("websearchagent:app", reload=True)
```

I was able to run this on my local

**Comment by manthanguptaa** [comment]
@MichaelXF the same issue is with Claude. We don't support asynchronous response on it and we will work on raising a clearer error message for a better developer experience

Can you please use `use_async=False` param like in my reply above to resolve the issue?

**Comment by manthanguptaa** [comment]
@epicalxyz I wasn't able to replicate the issue with Ollama. Can you please share your code block for me to test out and help you better?

**Comment by epicalxyz** [comment]
> @epicalxyz I wasn't able to replicate the issue with Ollama. Can you please share your code block for me to test out and help you better?

`from phi.agent import Agent
from phi.model.ollama import Ollama
from phi.tools.duckduckgo import DuckDuckGo

web_agent = Agent(
    name="Web Agent",
    model=Ollama(id="llama3.2:3b-instruct-fp16"),
    tools=[DuckDuckGo()],
    show_tool_calls=True,
    markdown=True,
)
web_agent.print_response("Whats happening in France?", stream=True)`

**Comment by manthanguptaa** [comment]
@epicalxyz I am able to run your example. I ran it with llama3.2

```
from phi.agent import Agent
from phi.model.ollama import Ollama
from phi.storage.agent.sqlite import SqlAgentStorage
from phi.tools.duckduckgo import DuckDuckGo
from phi.tools.yfinance import YFinanceTools
from phi.playground import Playground, serve_playground_app

web_agent = Agent(
    name="Web Agent",
    model=Ollama(id="llama3.2"),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    storage=SqlAgentStorage(table_name="web_agent", db_file="agents.db"),
    add_history_to_messages=True,
    markdown=True,
)

finance_agent = Agent(
    name="Finance Agent",
    model=Ollama(id="llama3.2"),
    tools=[YFinanceTools(stock_price=True, analyst_recommendations=True, company_info=True, company_news=True)],
    instructions=["Use tables to display data"],
    storage=SqlAgentStorage(table_name="finance_agent", db_file="agents.db"),
    add_history_to_messages=True,
    markdown=True,
)

app = Playground(agents=[finance_agent, web_agent]).get_app()

if __name__ == "__main__":
    serve_playground_app("playground:app", reload=True)
```

**Comment by epicalxyz** [comment]
> @epicalxyz I am able to run your example. I ran it with llama3.2
> 
> ```
> from phi.agent import Agent
> from phi.model.ollama import Ollama
> from phi.storage.agent.sqlite import SqlAgentStorage
> from phi.tools.duckduckgo import DuckDuckGo
> from phi.tools.yfinance import YFinanceTools
> from phi.playground import Playground, serve_playground_app
> 
> web_agent = Agent(
>     name="Web Agent",
>     model=Ollama(id="llama3.2"),
>     tools=[DuckDuckGo()],
>     instructions=["Always include sources"],
>     storage=SqlAgentStorage(table_name="web_agent", db_file="agents.db"),
>     add_history_to_messages=True,
>     markdown=True,
> )
> 
> finance_agent = Agent(
>     name="Finance Agent",
>     model=Ollama(id="llama3.2"),
>     tools=[YFinanceTools(stock_price=True, analyst_recommendations=True, company_info=True, company_news=True)],
>     instructions=["Use tables to display data"],
>     storage=SqlAgentStorage(table_name="finance_agent", db_file="agents.db"),
>     add_history_to_messages=True,
>     markdown=True,
> )
> 
> app = Playground(agents=[finance_agent, web_agent]).get_app()
> 
> if __name__ == "__main__":
>     serve_playground_app("playground:app", reload=True)
> ```
> 
> EDIT: I tried with `llama3.2:3b-instruct-fp16` model and it works well

Don't know why I'm getting these errors. Anyway, thanks for your help.

**Comment by zaizou** [comment]
Hi @manthanguptaa ,
The code works when I pass use_async=False, thank you for the solution.
maybe a default value or an error message would be helpful.
