### ISSUE TITLE
Crawl4AI tool has error

### ISSUE THREAD

**Issue by vanetreg** [phidatahq/phidata#1556]
I tweaked example code from here:
https://docs.phidata.com/tools/crawl4ai
and used this code:
```
from phi.agent import Agent
from phi.model.openai import OpenAIChat
from phi.tools.crawl4ai_tools import Crawl4aiTools
from dotenv import load_dotenv

load_dotenv()

agent = Agent(
    model=OpenAIChat(id="gpt-4o"),
    tools=[Crawl4aiTools(max_length=None)],
    show_tool_calls=True
)
agent.print_response("Summarize me the key points of this: https://blog.google/products/gemini/google-gemini-deep-research/")
```
but I've got error:
```
(phidata-venv) PS D:\Projects\AI_testing\phidata> python .\crawl4ai_example.py
▰▰▱▱▱▱▱ Thinking...INFO:httpx:HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
WARNING  Could not run function web_crawler(url=https://blog.google/products/gemini/google-gemini-deep-research, max_length=500)
ERROR    'NoneType' object is not callable
         Traceback (most recent call last):
           File "D:\Projects\AI_testing\phidata\phidata-venv\Lib\site-packages\phi\tools\function.py", line 313, in execute
             self.result = self.function.entrypoint(**entrypoint_args, **self.arguments)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "D:\Projects\AI_testing\phidata\phidata-venv\Lib\site-packages\pydantic\_internal\_validate_call.py", line 38, in wrapper_function
             return wrapper(*args, **kwargs)
                    ^^^^^^^^^^^^^^^^^^^^^^^^
           File "D:\Projects\AI_testing\phidata\phidata-venv\Lib\site-packages\pydantic\_internal\_validate_call.py", line 111, in __call__
             res = self.__pydantic_validator__.validate_python(pydantic_core.ArgsKwargs(args, kwargs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "D:\Projects\AI_testing\phidata\phidata-venv\Lib\site-packages\phi\tools\crawl4ai_tools.py", line 35, in web_crawler
             crawler = WebCrawler(verbose=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^
         TypeError: 'NoneType' object is not callable
```

**phidata v2.7.2**
and
**crawl4ai v0.4.1**
is used.

**Comment by manthanguptaa** [comment]
Hey @vanetreg, I am able to replicate this error. Allow me some time to fix this issue.
