### ISSUE TITLE
multi_agent.py example not working with Ollama

### ISSUE THREAD

**Issue by kaijennissen** [phidatahq/phidata#1572]
I've tried to run the [multi-agent](https://docs.phidata.com/introduction#multi-agent-orchestration) example using Ollama.
However I get an error that I need an OpenAIKey

```openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable```

Full message:

```
Traceback (most recent call last):
  File "/Users/.../multi_agent.py", line 34, in <module>
    agent_team.print_response("Summarize analyst recommendations and share the latest news for NVDA", stream=True)
  File "/Users/.../.venv/lib/python3.11/site-packages/phi/agent/agent.py", line 2783, in print_response
    for resp in self.run(message=message, messages=messages, stream=True, **kwargs):
  File "/Users.../.venv/lib/python3.11/site-packages/phi/agent/agent.py", line 1794, in _run
    for model_response_chunk in self.model.response_stream(messages=messages_for_model):
  File "/Users/.../.venv/lib/python3.11/site-packages/phi/model/openai/chat.py", line 833, in response_stream
    for response in self.invoke_stream(messages=messages):
  File "/Users/.../.venv/lib/python3.11/site-packages/phi/model/openai/chat.py", line 369, in invoke_stream
    yield from self.get_client().chat.completions.create(
               ^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/phi/model/openai/chat.py", line 152, in get_client
    return OpenAIClient(**client_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/.../.venv/lib/python3.11/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable
```

```python
from phi.agent import Agent
from phi.model.ollama import Ollama

from phi.tools.duckduckgo import DuckDuckGo
from phi.tools.yfinance import YFinanceTools

web_agent = Agent(
    name="Web Agent",
    role="Search the web for information",
    model=Ollama(id="llama3.3"),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    show_tool_calls=True,
    markdown=True,
)

finance_agent = Agent(
    name="Finance Agent",
    role="Get financial data",
    model=Ollama(id="llama3.3"),
    tools=[YFinanceTools(stock_price=True, analyst_recommendations=True, company_info=True)],
    instructions=["Use tables to display data"],
    show_tool_calls=True,
    markdown=True,
)

agent_team = Agent(
    team=[web_agent, finance_agent],
    instructions=["Always include sources", "Use tables to display data"],
    show_tool_calls=True,
    markdown=True,
)

agent_team.print_response("Summarize analyst recommendations and share the latest news for NVDA", stream=True)

```

**Comment by manthanguptaa** [comment]
Hey @kaijennissen, try this out

```
from phi.agent import Agent
from phi.model.ollama import Ollama

from phi.tools.duckduckgo import DuckDuckGo
from phi.tools.yfinance import YFinanceTools

web_agent = Agent(
    name="Web Agent",
    role="Search the web for information",
    model=Ollama(id="llama3.3"),
    tools=[DuckDuckGo()],
    instructions=["Always include sources"],
    show_tool_calls=True,
    markdown=True,
)

finance_agent = Agent(
    name="Finance Agent",
    role="Get financial data",
    model=Ollama(id="llama3.3"),
    tools=[YFinanceTools(stock_price=True, analyst_recommendations=True, company_info=True)],
    instructions=["Use tables to display data"],
    show_tool_calls=True,
    markdown=True,
)

agent_team = Agent(
    model=Ollama(id="llama3.3"),
    team=[web_agent, finance_agent],
    instructions=["Always include sources", "Use tables to display data"],
    show_tool_calls=True,
    markdown=True,
)

agent_team.print_response("Summarize analyst recommendations and share the latest news for NVDA", stream=True)
```

**Comment by kaijennissen** [comment]
@manthanguptaa Thanks. I've also figured this out. Adding this to the docs could be helpful.

**Comment by ysolanky** [comment]
You're right @kaijennissen. Will update the example. Thanks for bringing this to our attention!
