### ISSUE TITLE
Error：sqlalchemy.exc.StatementError: (builtins.ValueError) expected 768 dimensions, not 0

### ISSUE THREAD

**Issue by ouening** [phidatahq/phidata#179]
**example:**`cookbook/llms/groq/rag/app.py` and `cookbook/llms/ollama/rag/app.py`

Error message:
```
Traceback (most recent call last):
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    context = constructor(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1486, in _init_compiled
    d_param = {
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1488, in <dictcomp>
    flattened_processors[key](compiled_params[key])
  File "/home/gaoya/.local/lib/python3.10/site-packages/pgvector/sqlalchemy/__init__.py", line 23, in process
    return to_db(value, self.dim)
  File "/home/gaoya/.local/lib/python3.10/site-packages/pgvector/utils/__init__.py", line 35, in to_db
    raise ValueError('expected %d dimensions, not %d' % (dim, len(value)))
ValueError: expected 768 dimensions, not 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/gaoya/.local/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 584, in _run_script
    exec(code, module.__dict__)
  File "/media/disk4t/LLM/phidata/cookbook/llms/groq/rag/app.py", line 170, in <module>
    main()
  File "/media/disk4t/LLM/phidata/cookbook/llms/groq/rag/app.py", line 141, in main
    rag_assistant.knowledge_base.load_documents(rag_documents, upsert=True)
  File "/home/gaoya/.local/lib/python3.10/site-packages/phi/knowledge/base.py", line 107, in load_documents
    self.vector_db.upsert(documents=documents)
  File "/home/gaoya/.local/lib/python3.10/site-packages/phi/vectordb/pgvector/pgvector2.py", line 224, in upsert
    sess.execute(stmt)
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2200, in _execute_internal
    result = conn.execute(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1422, in execute
    return meth(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 514, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1644, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1825, in _execute_context
    self._handle_dbapi_exception(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2357, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    context = constructor(
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1486, in _init_compiled
    d_param = {
  File "/home/gaoya/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1488, in <dictcomp>
    flattened_processors[key](compiled_params[key])
  File "/home/gaoya/.local/lib/python3.10/site-packages/pgvector/sqlalchemy/__init__.py", line 23, in process
    return to_db(value, self.dim)
  File "/home/gaoya/.local/lib/python3.10/site-packages/pgvector/utils/__init__.py", line 35, in to_db
    raise ValueError('expected %d dimensions, not %d' % (dim, len(value)))
sqlalchemy.exc.StatementError: (builtins.ValueError) expected 768 dimensions, not 0
[SQL: INSERT INTO ai.groq_rag_documents_ollama (id, name, meta_data, content, embedding, usage, content_hash) VALUES (%(id)s::VARCHAR, %(name)s::VARCHAR, %(meta_data)s::JSONB, %(content)s::VARCHAR, %(embedding)s, %(usage)s::JSONB, %(content_hash)s::VARCHAR) ON CONFLICT (id) DO UPDATE SET name = excluded.name, meta_data = excluded.meta_data, content = excluded.content, embedding = excluded.embedding, usage = excluded.usage, content_hash = excluded.content_hash]
[parameters: [{}]]
```

I have installed the packages in requirements.txt, but the rag example did not work for me. Hope for solution!

**Comment by ashpreetbedi** [comment]
Hi @ouening is ollama running? this error indicated that the embeddings did not get created?

**Comment by ouening** [comment]
Does the groq example also need ollama? I will try in my another computer

**Comment by ashpreetbedi** [comment]
Thank you @ouening , you are correct will use `ollama pull`

Love your help with this :) thank you
