### ISSUE TITLE
AttributeError: module 'click' has no attribute 'get_os_args'

### ISSUE THREAD

**Issue by NetFlareSuperAdmin** [phidatahq/phidata#204]
Following the instructions to run RAG with Phi3 gives:

streamlit run cookbook/llms/ollama/rag/app.py
Traceback (most recent call last):
  File "/Users/gangcai/opt/miniconda3/bin/streamlit", line 8, in <module>
    sys.exit(main())
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/streamlit/cli.py", line 191, in main_run
    _main_run(target, args, flag_options=kwargs)
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/streamlit/cli.py", line 212, in _main_run
    command_line = _get_command_line_as_string()
  File "/Users/gangcai/opt/miniconda3/lib/python3.9/site-packages/streamlit/cli.py", line 201, in _get_command_line_as_string
    cmd_line_as_list.extend(click.get_os_args())
AttributeError: module 'click' has no attribute 'get_os_args'

How can I fix this? Would love to see it run. Thanks!

**Comment by ysolanky** [comment]
@Okdesk I am not able to replicate this error and it seems like it's from [Streamlit](https://discuss.streamlit.io/t/attributeerror-module-click-has-no-attribute-get-os-args/23621/13)

Can you make sure you upgraded your libraries to match the [requirements](https://github.com/phidatahq/phidata/blob/main/cookbook/llms/ollama/rag/requirements.txt)

**Comment by ysolanky** [comment]
Closing this issue due to inactivity. Please reopen if the issue persists
